### ISSUE TITLE
18.1.2023 Neovim text not visually pleasing on one side of the coaster

### ISSUE THREAD

**Issue by OlliGranlund** [Wa1tee/Neovim_coasters#1]
Hello sir!

I stumbled upon your project and was really keen on producing some of these for my own use. I noticed however a small issue that is blocking me from producing these. The text "Neovim" could be smaller font as on one side of the coaster the text gets really close to the right column of content and doesn't look aesthetically pleasing.

If you look at the instructions, they have a pretty distinct spot where they wrap over to the next line but the "Neovim" text doesn't seem to follow that rule.

**Comment by Wa1tee** [comment]
Nice

**Comment by Wa1tee** [comment]
Okay actually fixed it now
